menu:
    Home: /
    Blog: /blog/
    Archive: /archives/
    Gallery: /gallery/
    About: /about/
    # Rss: /atom.xml

title: 14 号院
description: Jeremy Fan's Blog，14 号院

favicon: /favicon.ico
logo: /logo.png

# Copyright Infomation
startyear: 2017