menu:
    Home: /
    Archive: /archives/
    Contact: "http://jeremyfan.name"
    # Rss: /atom.xml

title: 14 号院
description: Jeremy Fan's Blog，14 号院

favicon: /favicon.ico
logo: /logo.png

# Copyright Infomation
startyear: 2017